SoftwareProjectManagementSystemWebApp/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SoftwareProjectManagementSystemWebApp.Manager;
using SoftwareProjectManagementSystemWebApp.Models;
using SoftwareProjectManagementSystemWebApp.Models.ViewModels;
using SoftwareProjectManagementSystemWebApp.Utility;

namespace SoftwareProjectManagementSystemWebApp.Controllers
{
    public class TaskController : Controller
    {
        private ProjectManager projectManager;
        private TaskManager taskManager;
        private AuthenticationManager authManager;
        private UserManager userManager;

        public TaskController()
        {
            projectManager = new ProjectManager();
            taskManager = new TaskManager();
            authManager = new AuthenticationManager();
            userManager = new UserManager();
        }

        // 
        [HttpGet]
        public ActionResult AddTask()
        {
            if (CheckAuthProjectManagerAndOther() == 0)
            {
                ViewBag.ErrorMessage = "Log in first";
                return RedirectToAction("LogIn", "UserAuthentication");
            }
            else if (CheckAuthProjectManagerAndOther() == 1)
            {
                User user = userManager.GetUserById(Convert.ToInt32(Session["UserId"]));

                ViewBag.UserName = user.Name;

                ViewBag.Projects = projectManager.GetAllProjectsForDropDown();

                return View();
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        public ActionResult AddTask(Task task)
        {
            if (CheckAuthProjectManagerAndOther() == 0)
            {
                ViewBag.ErrorMessage = "Log in first";
                return RedirectToAction("LogIn", "UserAuthentication");
            }
            else if (CheckAuthProjectManagerAndOther() == 1)
            {
                User user = userManager.GetUserById(Convert.ToInt32(Session["UserId"]));

                ViewBag.UserName = user.Name;

                if (ModelState.IsValid)
                {
                    task.AssignedById = Convert.ToInt32(Session["UserId"]);
                    task.ActionTime = DateTime.Now.ToString();
                    task.ActionDone = ActionUtility.ActionInsert;

                    ViewBag.Response = taskManager.AddTask(task);

                    ViewBag.Projects = projectManager.GetAllProjectsForDropDown();
                    ModelState.Clear();
                    return View();
                }
                else
                {
                    ViewBag.Response = "Fill up all fields correctly";
                    ViewBag.Projects = projectManager.GetAllProjectsForDropDown();
                    return View(task);
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        // get user by project
        public JsonResult GetUserByProject(int projectId)
        {
            return Json(projectManager.GetUserByProject(projectId));
        }

        // update task
        [HttpGet]
        public ActionResult UpdateTask(int taskId)
        {
            if (CheckAuthProjectManagerAndOther() == 0)
            {
                ViewBag.ErrorMessage = "Log in first";
                return RedirectToAction("LogIn", "UserAuthentication");
            }
            else if (CheckAuthProjectManagerAndOther() == 1)
            {
                User user = userManager.GetUserById(Convert.ToInt32(Session["UserId"]));

                ViewBag.UserName = user.Name;

                if (taskManager.IsTaskExists(taskId))
                {
                    TaskListViewModel taskById = taskManager.GetTasksByTaskId(taskId);

                    Task task = new Task();
                    task.Id = taskById.Id;
                    task.ProjectId = taskById.ProjectId;
                    task.Description = taskById.Description;
                    task.DueDate = taskById.DueDate;
                    task.Priority = taskById.Priority;
                    task.AssignedToId = taskById.AssignedToId;

                    ViewBag.ProjectName = taskById.ProjectName;
                    ViewBag.UserName = taskById.AssignedTo;
                    ViewBag.SelectedIndex = taskById.Priority;

                    return View(task);
                }
                else
                {
                    return HttpNotFound();
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        public ActionResult UpdateTask(Task task)
        {
            if (CheckAuthProjectManagerAndOther() == 0)
            {
                ViewBag.ErrorMessage = "Log in first";
                return RedirectToAction("LogIn", "UserAuthentication");
            }
            else if (CheckAuthProjectManagerAndOther() == 1)
            {
                User user = userManager.GetUserById(Convert.ToInt32(Session["UserId"]));

                ViewBag.UserName = user.Name;

                if (ModelState.IsValid)
                {
                    task.AssignedById = Convert.ToInt32(Session["UserId"]);
                    task.ActionDone = ActionUtility.ActionUpdate;
                    task.ActionTime = DateTime.Now.ToString();

                    ViewBag.Response = taskManager.UpdateTask(task);


                    TaskListViewModel taskById = taskManager.GetTasksByTaskId(task.Id);

                    task.Id = taskById.Id;
                    task.ProjectId = taskById.ProjectId;
                    task.Description = taskById.Description;
                    task.DueDate = taskById.DueDate;
                    task.Priority = taskById.Priority;
                    task.AssignedToId = taskById.AssignedToId;

                    ViewBag.ProjectName = taskById.ProjectName;
                    ViewBag.UserName = taskById.AssignedTo;
                    ViewBag.SelectedIndex = taskById.Priority;

                    return View(task);
                }
                else
                {
                    ViewBag.Response = "Fill Up all fields correctly";

                    TaskListViewModel taskById = taskManager.GetTasksByTaskId(task.Id);

                    task.Id = taskById.Id;
                    task.ProjectId = taskById.ProjectId;
                    task.Description = taskById.Description;
                    task.DueDate = taskById.DueDate;
                    task.Priority = taskById.Priority;
                    task.AssignedToId = taskById.AssignedToId;

                    ViewBag.ProjectName = taskById.ProjectName;
                    ViewBag.UserName = taskById.AssignedTo;
                    ViewBag.SelectedIndex = taskById.Priority;

                    return View(task);
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        // check auth with project manager and other
        public int CheckAuthProjectManagerAndOther()
        {
            int userId = Convert.ToInt32(Session["UserId"]);

            if (authManager.CheckDesignation(userId) == 5)
            {
                return 0;
            }
            else if (authManager.CheckDesignation(userId) == 2 || authManager.CheckDesignation(userId) == 3)
            {
                return 1;
            }
            else
            {
                return 2;
            }
        }
    }
}

SoftwareProjectManagementSystemWebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SoftwareProjectManagementSystemWebApp.Manager;
using SoftwareProjectManagementSystemWebApp.Models;
using SoftwareProjectManagementSystemWebApp.Utility;

namespace SoftwareProjectManagementSystemWebApp.Controllers
{
    public class UserController : Controller
    {
        private UserManager userManager;
        private DesignationManager designationManager;
        private AuthenticationManager authManager;
        
        public UserController()
        {
            userManager = new UserManager();
            designationManager = new DesignationManager();
            authManager = new AuthenticationManager();
        }

        // save user (for IT Admin) 
        [HttpGet]
        public ActionResult SaveUser()
        {
            if (CheckAuthITAdmin() == 0)
            {
                ViewBag.ErrorMessage = "Log in first";
                return RedirectToAction("LogIn","UserAuthentication");
            }
            else if (CheckAuthITAdmin() == 1)
            {
                User user = userManager.GetUserById(Convert.ToInt32(Session["UserId"]));

                ViewBag.UserName = user.Name;
                ViewBag.Designations = designationManager.GetDesignationForDropDown();
                return View();
            }
            else
            {
                return HttpNotFound();
            }
            
        }

        [HttpPost]
        public ActionResult SaveUser(User user)
        {
            if (CheckAuthITAdmin() == 0)
            {
                ViewBag.ErrorMessage = "Log in first";
                return RedirectToAction("LogIn", "UserAuthentication");
            }
            else if (CheckAuthITAdmin() == 1)
            {
                User userName = userManager.GetUserById(Convert.ToInt32(Session["UserId"]));

                ViewBag.UserName = userName.Name;

                if (ModelState.IsValid)
                {
                    user.ActionBy = "IT Admin";
                    user.ActionDone = ActionUtility.ActionInsert;
                    user.ActionTime = DateTime.Now.ToString();

                    int saved = userManager.SaveUser(user);

                    if (saved == 1)
                    {
                        ViewBag.Message = "Saved Successfully";

                        ModelState.Clear();
                        ViewBag.Designations = designationManager.GetDesignationForDropDown();
                        return View();
                    }
                    else if (saved == 2)
                    {
                        ViewBag.Message = "Email Must be Unique";

                        ViewBag.Designations = designationManager.GetDesignationForDropDown();
                        return View(user);
                    }
                    else
                    {
                        ViewBag.Message = "Save Failed";

                        ViewBag.Designations = designationManager.GetDesignationForDropDown();
                        return View(user);
                    }
                }
                else
                {
                    ViewBag.Message = "Fill up all fields";

                    ViewBag.Designations = designationManager.GetDesignationForDropDown();
                    return View(user);
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

         // view all users (for IT Admin)
        [HttpGet]
        public ActionResult ViewAllUsers()
        {
            if (CheckAuthITAdmin() == 0)
            {
                ViewBag.ErrorMessage = "Log in first";
                return RedirectToAction("LogIn", "UserAuthentication");
            }
            else if (CheckAuthITAdmin() == 1)
            {
                User user = userManager.GetUserById(Convert.ToInt32(Session["UserId"]));

                ViewBag.UserName = user.Name;
                ViewBag.ViewAllUsers = userManager.GetAllUsers();
                return View();
            }
            else
            {
                return HttpNotFound();
            }

            
        }

        //// reset password (for IT Admin)
        [HttpGet]
        public ActionResult ResetPassword(int id)
        {
            if (CheckAuthITAdmin() == 0)
            {
                ViewBag.ErrorMessage = "Log in first";
                return RedirectToAction("LogIn", "UserAuthentication");
            }
            else if (CheckAuthITAdmin() == 1)
            {
                User user = userManager.GetUserById(Convert.ToInt32(Session["UserId"]));

                ViewBag.UserName = user.Name;
                if (userManager.IsUserExists(id))
                {
                    int resetPassword = userManager.ResetPassword(id);

                    if (resetPassword == 1)
                    {
                        ViewBag.Message = "Successfully reset";
                    }
                    else
                    {
                        ViewBag.Message = "Reset Failed";
                    }

                    return View();
                }
                else
                {
                    return HttpNotFound();
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        // update user (for IT Admin)
        [HttpGet]
        public ActionResult UpdateUser(int id)
        {
            if (CheckAuthITAdmin() == 0)
            {
                ViewBag.ErrorMessage = "Log in first";
                return RedirectToAction("LogIn", "UserAuthentication");
            }
            else if (CheckAuthITAdmin() == 1)
            {
                User userName = userManager.GetUserById(Convert.ToInt32(Session["UserId"]));

                ViewBag.UserName = userName.Name;
                if (userManager.IsUserExists(id))
                {
                    User user = userManager.GetUserById(id);

                    ViewBag.NowStatus = user.Status;
                    ViewBag.DesignationIndex = user.DesignationId;
                    ViewBag.Designations = designationManager.GetDesignationForDropDown();

                    return View(user);
                }
                else
                {
                    return HttpNotFound();
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        public ActionResult UpdateUser(User user)
        {
            if (CheckAuthITAdmin() == 0)
            {
                ViewBag.ErrorMessage = "Log in first";
                return RedirectToAction("LogIn", "UserAuthentication");
            }
            else if (CheckAuthITAdmin() == 1)
            {
                User userName = userManager.GetUserById(Convert.ToInt32(Session["UserId"]));

                ViewBag.UserName = userName.Name;

                if (ModelState.IsValid)
                {
                    user.ActionBy = "IT Admin";
                    user.ActionDone = ActionUtility.ActionUpdate;
                    user.ActionTime = DateTime.Now.ToString();

                    int updated = userManager.UpdateUser(user);

                    if (updated == 1)
                    {
                        ViewBag.Message = "Successfull";
                    }
                    else if (updated == 2)
                    {
                        ViewBag.Message = "Email already exists";
                    }
                    else if (updated == 0)
                    {
                        ViewBag.Message = "Save Failed";
                    }

                    User userInfo = userManager.GetUserById(user.Id);

                    ViewBag.NowStatus = userInfo.Status;
                    ViewBag.DesignationIndex = userInfo.DesignationId;
                    ViewBag.Designations = designationManager.GetDesignationForDropDown();

                    return View(userInfo);

                }
                else
                {
                    ViewBag.Message = "Fill up all fields";

                    User userInfo = userManager.GetUserById(user.Id);

                    ViewBag.NowStatus = userInfo.Status;
                    ViewBag.DesignationIndex = userInfo.DesignationId;
                    ViewBag.Designations = designationManager.GetDesignationForDropDown();

                    return View(userInfo);
                }
            }
            else
            {
                return HttpNotFound();
            }
        }

        // check IT Admin for auth
        public int CheckAuthITAdmin()
        {
            int userId = Convert.ToInt32(Session["UserId"]);

            if (authManager.CheckDesignation(userId) == 5)
            {
                return 0;
            }
            else if (authManager.CheckDesignation(userId) == 1)
            {
                return 1;
            }
            else
            {
                return 2;
            }
        }
	}
}

SoftwareProjectManagementSystemWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SoftwareProjectManagementSystemWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SoftwareProjectManagementSystemWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="jumbotron">
    <h1>Project Management System</h1>
    <p class="lead">Simple Software for a software firm to manage project files</p>

</div>

<div class="row">
    @{
        if (ViewBag.Designation.Equals("IT Admin"))
        {
            <div class="col-md-4">
                <h2>Add User</h2>
                <p>@Html.ActionLink("Go=>>", "SaveUser", "User", null, new { @class = "btn btn-default" })</p>
            </div>

            <div class="col-md-4">
                <h2>View All User</h2>
                <p>@Html.ActionLink("Go=>>", "ViewAllUsers", "User", null, new { @class = "btn btn-default" })</p>
            </div>
        }
        else if (ViewBag.Designation.Equals("Project Manager"))
        {
            <div class="col-md-4">
                <h2>Add New Project</h2>
                <p>@Html.ActionLink("Go=>>", "AddProject", "Project", null, new { @class = "btn btn-default" })</p>
            </div>

            <div class="col-md-4">
                <h2>View Projects</h2>
                <p>@Html.ActionLink("Go=>>", "ViewAllProject", "Project", null, new { @class = "btn btn-default" })</p>
            </div>

            <div class="col-md-4">
                <h2>Assign User</h2>
                <p>@Html.ActionLink("Go=>>", "AssignUser", "Project", null, new { @class = "btn btn-default" })</p>
            </div>

            <div class="col-md-4">
                <h2>Involved Projects</h2>
                <p>@Html.ActionLink("Go=>>", "ViewProjectInvolve", "Project", null, new { @class = "btn btn-default" })</p>
            </div>

            <div class="col-md-4">
                <h2>Add Task</h2>
                <p>@Html.ActionLink("Go=>>", "AddTask", "Task", null, new { @class = "btn btn-default" })</p>
            </div>

            <div class="col-md-4">
                <h2>Add Comment</h2>
                <p>@Html.ActionLink("Go=>>", "AddComment", "Comment", null, new { @class = "btn btn-default" })</p>
            </div>
        }
        else
        {
            <div class="col-md-4">
                <h2>Assign User</h2>
                <p>@Html.ActionLink("Go=>>", "AssignUser", "Project", null, new { @class = "btn btn-default" })</p>
            </div>

            <div class="col-md-4">
                <h2>Involved Projects</h2>
                <p>@Html.ActionLink("Go=>>", "ViewProjectInvolve", "Project", null, new { @class = "btn btn-default" })</p>
            </div>

            <div class="col-md-4">
                <h2>Add Task</h2>
                <p>@Html.ActionLink("Go=>>", "AddTask", "Task", null, new { @class = "btn btn-default" })</p>
            </div>

            <div class="col-md-4">
                <h2>Add Comment</h2>
                <p>@Html.ActionLink("Go=>>", "AddComment", "Comment", null, new { @class = "btn btn-default" })</p>
            </div>
        }
    }
</div>

SoftwareProjectManagementSystemWebApp/Views/Home/home.cshtml
@{
    ViewBag.Title = "home";

}

<h2>home</h2>

<!DOCTYPE html>
<html>
<head>
    <title>KDA PORTAL</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <link rel="stylesheet" href="dashboard.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-+xnqFbV7vC4UJmtV7eGt/lLzrj5A/x5zUZsxr2wzjvEbvCg/lPnfhLR+E8Nnj5D5Bu/3qX5w5U8Y5Y5a5w==" crossorigin="anonymous" />
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js"></script>


</head>
<body>

    <div class="topnav" id="topnav">

        <a href="javascript:void(0)"
           style="font-size: 30px; cursor: pointer;color: white;"><i class="fa fa-fw fa-bar" onclick="toggleNav()">&#9776;</i></a>

        <div class="logo"> PROPERTIES &nbsp; PORTAL</div>
        <a href="#dashborad" style="font-size: 30px; cursor: pointer;text-decoration: none;"></a>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" id="search" placeholder="Search" aria-label="Search" onchange="openSearch()">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="search" onchange="openSearch()">Search</button>
        </form>
        <a href="#"><span class="glyphicon glyphicon-log-in"></span> Logout</a>

    </div>
    <div class="sidebar" id="sidebar">
        <p style="text-decoration: none;color: white;text-align: center;font-size:xx-large;">KDA WORLD</p>
        <a href="dashboard.html" style="text-decoration: none;"><i class="fa fa-fw fa-dashboard"></i>Dashboard</a>
        <a href="home.html" style="text-decoration: none;"><i class="fa fa-fw fa-home"></i> Home</a>
        <a href="about.html" style="text-decoration: none;"><i class="fa fa-fw fa-user"></i> About</a>
        <a href="properties.html" style="text-decoration: none;"><i class="fa fa-fw fa-heart"></i> Properties</a>
    </div>





    <div class="main" id="main" style="background-color:#60B76C  ;">
        <h1 class="dashboard-title">DASHBOARD</h1>
        <div style="display: flex; flex-wrap: wrap;background-color:#60B76C  ;" class="main" id="main">

            <!-----------------------------------MAIN BODY DIV---------------------------------------->
            <div class="div1">
                <!--user visit-->
                <h2><b>Views</b></h2>
                <div id="visit-count"></div>
            </div>
            <!--------------------------------------------------------------------------------->
            <div class="div2">
                <!--user click------------------->
                <h2><b>Click Anywhere</b></h2>
                <div id="counter-container">
                    <div id="click-count">0</div>
                </div>
                <!---------------------------->
            </div>
            <div class="div3" id='calendar'>
                <!--calender-->
                <h2><b>Calender</b></h2>
            </div>
            <div class="div4 ">

                <div id='clock'></div>

                <div class="clock-hand hour"></div>
                <div class="clock-hand minute"></div>
                <div class="clock-hand second"></div>
                <h2><b>Clock</b></h2>
            </div>
            <!------------------------------------------------------------------------>
            <div class="div5">
                <!--performance graph-->
                <div id="chart" style="height: 800px;width: 80%;">
                    <h2><b>Graph</b></h2>
                    <canvas id="performance-chart"></canvas>

                </div>
            </div>
            <!------------------------------------------------------------------------>
            <!------------------------------------------------------------------------>

            <div class="div6">
                <h2><b>Social Media</b></h2>
                <div class="progress-bar-container" id="progress-bar-1">
                    <div class="bar1" id="bar-1"></div>
                    <div class="percentage" id="percentage-1"></div>
                </div>
                <h2><b>WebSite Performance</b></h2>
                <div class="progress-bar-container" id="progress-bar-2">
                    <div class="bar2" id="bar-2"></div>
                    <div class="percentage" id="percentage-2"></div>
                </div>

            </div>

            <!------------------------------------------------------------------------>
        </div>
        <!--------------------------------------------------------------------------->

    </div>

    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


  
</body>
</html>